#!/bin/bash

ICONS="/usr/share/icons/breeze-dark/actions/32"
MENU="img:$ICONS/system-log-out.svg:text:Logout\nimg:$ICONS/system-suspend.svg:text:Suspend\nimg:$ICONS/system-reboot.svg:text:Reboot\nimg:$ICONS/system-shutdown.svg:text:Shutdown"

CHOICE=$(echo -e "$MENU" | wofi --dmenu -L 5 -W 15% --cache-file /dev/null | awk '{print tolower($1)}')

case $CHOICE in
  "logout")
    hyperctl dispatch exit 0;;
  "suspend")
    systemctl suspend;;
  "reboot")
    systemctl reboot;;
  "shutdown")
    systemctl poweroff -i;;
esac
