#!/bin/bash

ICONS="/usr/share/icons/breeze-dark/actions/32"
MENU="img:$ICONS/system-log-out.svg:text:Logout\nimg:$ICONS/system-suspend.svg:text:Suspend\nimg:$ICONS/system-hibernate.svg:text:Hibernate\nimg:$ICONS/system-reboot.svg:text:Reboot\nimg:$ICONS/system-shutdown.svg:text:Poweroff"

CHOICE=$(echo -e "$MENU" | wofi --dmenu -L 6 -W 1% --cache-file /dev/null -p "Power Menu" | awk '{print tolower($1)}')

case $CHOICE in
  "logout")
    hyperctl dispatch exit 0;;
  "suspend")
    systemctl suspend;;
  "hibernate")
    systemctl hibernate;;
  "reboot")
    systemctl reboot;;
  "poweroff")
    systemctl poweroff -i;;
esac
