#!/bin/sh
#
# dot_update
#
# `dot_update` handles installation, updates, things like that. Run it
# periodically to make sure you're on the latest and greatest.
set -x

export DOTFILES="$HOME/.dotfiles"

git submodule update --init --recursive

cd ~
vim +PluginInstall! +qall

~/.dotfiles/vim/bundle/YouCompleteMe/install.py --clang-completer --tern-completer --gocode-completer


exit 1
