#!/usr/bin/env bash

case "$1" in
    lock)
        xset s activate
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
        systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|reboot|shutdown]"
        exit 2
esac

exit 0
