#!/bin/zsh

sxhkd &

ws1=desktop
ws2=browse
ws3=code
ws4=edit
ws5=cli
ws6=media
ws7=communicate
ws8=8
ws9=9
ws10=10

bspc config border_width          0
bspc config window_gap            10
bspc config top_padding           28

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true

bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7

bspc desktop $ws2 -l monocle

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Firefox desktop=^2
bspc rule -a Thunderbird desktop=^5
bspc rule -a mplayer state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton -b &
feh --bg-scale ~/Pictures/Wallpapers/0134.jpg &
xss-lock -- i3lock -n -i ~/Pictures/0030.png &
$HOME/.config/lemonbuddy/launch.sh
xrdb ~/.Xresources

dropbox start &
