#!/bin/zsh

sxhkd &

ws1=home
ws2=chat
ws3=mail
ws4=browse
ws5=edit
ws6=code
ws7=cli
ws8=media
ws9=9
ws0=0

bspc config border_width          2
bspc config window_gap            5

MONITORS=$(xrandr -q | grep "*" | wc -l)

if [ "$MONITORS" -eq 3 ]; then
  xrandr --output HDMI2  --primary --auto --output HDMI3 --auto --right-of HDMI2 --output LVDS1 --auto --left-of HDMI2
  bspc monitor LVDS1 -d $ws1 $ws2 $ws3
  bspc monitor HDMI2 -d $ws4 $ws6 $ws8
  bspc monitor HDMI3 -d $ws5 $ws7
elif [ "$MONITORS" -eq 2 ]; then
  xrandr --output HDMI2  --primary --auto --output HDMI3 --auto --right-of HDMI2
  bspc monitor HDMI2 -d $ws1 $ws2 $ws3 $ws4 $ws5
  bspc monitor HDMI3 -d $ws6 $ws7 $ws8
  bspc monitor HDMI2 -s HDMI3
  bspc monitor LVDS1 -r
elif [ "$MONITORS" -eq 1 ]; then
  xrandr --output LVDS1 --primary --auto
  bspc monitor LVDS1 -d $ws1 $ws2 $ws3 $ws6 $ws7 $ws4 $ws5
  bspc monitor HDMI2 -r
  bspc monitor HDMI3 -r
fi

bspc config split_ratio           0.52
bspc config single_monocle        true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus        true
bspc config adaptive_raise        true

bspc rule -a Firefox desktop=$ws4
bspc rule -a rocket.chat desktop=$ws2
bspc rule -a Thunderbird desktop=$ws3
bspc rule -a lxappearance state=floating
bspc rule -a VirtualBox state=floating

xrdb ~/.Xresources
feh --bg-fill --recursive ~/Pictures/Wallpapers/0040.jpg &
compton -b &
$HOME/.config/polybar/launch.sh
udiskie -q &
xss-lock -- physlock -sm &
