[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  # "monitors",
  "shift_monitors",
  "toggle_dpms",
  # "magnify",
  "expose",
  "shift_monitors",
  "workspaces_follow_focus",
]

[workspaces_follow_focus]
max_workspaces = 9

[expose]
include_special = false

[scratchpads.term]
    command = "kitty --title scratchpad"
    margin = 50
    unfocus = "hide"
    animation = "fromTop"
    lazy = true

[scratchpads.btm]
    command = "kitty --title scratchpad -e btm"
    margin = 50
    unfocus = "hide"
    animation = "fromTop"
    lazy = true
